# Generated by Django 5.2.4 on 2025-07-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
